"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class NestedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: typing.Text = ...
    value: typing.Text = ...
    def __init__(
        self,
        *,
        key: typing.Text = ...,
        value: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]
    ) -> None: ...

global___NestedMessage = NestedMessage

class ExampleMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class SomeEnum(_SomeEnum, metaclass=_SomeEnumEnumTypeWrapper):
        pass
    class _SomeEnum:
        V = typing.NewType("V", builtins.int)
    class _SomeEnumEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SomeEnum.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        unspecified = ExampleMessage.SomeEnum.V(0)
        first = ExampleMessage.SomeEnum.V(1)
        second = ExampleMessage.SomeEnum.V(2)
    unspecified = ExampleMessage.SomeEnum.V(0)
    first = ExampleMessage.SomeEnum.V(1)
    second = ExampleMessage.SomeEnum.V(2)
    class MapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    INT32_FIELD_NUMBER: builtins.int
    INT64_FIELD_NUMBER: builtins.int
    UINT32_FIELD_NUMBER: builtins.int
    UINT64_FIELD_NUMBER: builtins.int
    DOUBLE_FIELD_NUMBER: builtins.int
    FLOAT_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    ENUM_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    NESTED_FIELD_NUMBER: builtins.int
    STRINGLIST_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    SFIXED32_FIELD_NUMBER: builtins.int
    SFIXED64_FIELD_NUMBER: builtins.int
    SINT32_FIELD_NUMBER: builtins.int
    SINT64_FIELD_NUMBER: builtins.int
    FIXED32_FIELD_NUMBER: builtins.int
    FIXED64_FIELD_NUMBER: builtins.int
    ONEOFSTRING_FIELD_NUMBER: builtins.int
    ONEOFINT32_FIELD_NUMBER: builtins.int
    MAP_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    int32: builtins.int = ...
    int64: builtins.int = ...
    uint32: builtins.int = ...
    uint64: builtins.int = ...
    double: builtins.float = ...
    float: builtins.float = ...
    bool: builtins.bool = ...
    enum: global___ExampleMessage.SomeEnum.V = ...
    string: typing.Text = ...
    @property
    def nested(self) -> global___NestedMessage: ...
    @property
    def stringlist(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ]: ...
    bytes: builtins.bytes = ...
    sfixed32: builtins.int = ...
    sfixed64: builtins.int = ...
    sint32: builtins.int = ...
    sint64: builtins.int = ...
    fixed32: builtins.int = ...
    fixed64: builtins.int = ...
    oneofstring: typing.Text = ...
    oneofint32: builtins.int = ...
    @property
    def map(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def duration(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        int32: builtins.int = ...,
        int64: builtins.int = ...,
        uint32: builtins.int = ...,
        uint64: builtins.int = ...,
        double: builtins.float = ...,
        float: builtins.float = ...,
        bool: builtins.bool = ...,
        enum: global___ExampleMessage.SomeEnum.V = ...,
        string: typing.Text = ...,
        nested: typing.Optional[global___NestedMessage] = ...,
        stringlist: typing.Optional[typing.Iterable[typing.Text]] = ...,
        bytes: builtins.bytes = ...,
        sfixed32: builtins.int = ...,
        sfixed64: builtins.int = ...,
        sint32: builtins.int = ...,
        sint64: builtins.int = ...,
        fixed32: builtins.int = ...,
        fixed64: builtins.int = ...,
        oneofstring: typing.Text = ...,
        oneofint32: builtins.int = ...,
        map: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        timestamp: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        duration: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "duration",
            b"duration",
            "nested",
            b"nested",
            "oneof",
            b"oneof",
            "oneofint32",
            b"oneofint32",
            "oneofstring",
            b"oneofstring",
            "timestamp",
            b"timestamp",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "bool",
            b"bool",
            "bytes",
            b"bytes",
            "double",
            b"double",
            "duration",
            b"duration",
            "enum",
            b"enum",
            "fixed32",
            b"fixed32",
            "fixed64",
            b"fixed64",
            "float",
            b"float",
            "int32",
            b"int32",
            "int64",
            b"int64",
            "map",
            b"map",
            "nested",
            b"nested",
            "oneof",
            b"oneof",
            "oneofint32",
            b"oneofint32",
            "oneofstring",
            b"oneofstring",
            "sfixed32",
            b"sfixed32",
            "sfixed64",
            b"sfixed64",
            "sint32",
            b"sint32",
            "sint64",
            b"sint64",
            "string",
            b"string",
            "stringlist",
            b"stringlist",
            "timestamp",
            b"timestamp",
            "uint32",
            b"uint32",
            "uint64",
            b"uint64",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["oneof", b"oneof"]
    ) -> typing.Optional[typing_extensions.Literal["oneofstring", "oneofint32"]]: ...

global___ExampleMessage = ExampleMessage
