# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x65xample/example.proto\x12\x07\x65xample\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto"@\n\rSimpleMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\x12\x0f\n\x07measure\x18\x03 \x01(\x02"+\n\rNestedMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"\x1f\n\x0e\x44\x65\x63imalMessage\x12\r\n\x05value\x18\x01 \x01(\t"\xb7\x05\n\x0e\x45xampleMessage\x12\r\n\x05int32\x18\x01 \x01(\x05\x12\r\n\x05int64\x18\x02 \x01(\x03\x12\x0e\n\x06uint32\x18\x03 \x01(\r\x12\x0e\n\x06uint64\x18\x04 \x01(\x04\x12\x0e\n\x06\x64ouble\x18\x05 \x01(\x01\x12\r\n\x05\x66loat\x18\x06 \x01(\x02\x12\x0c\n\x04\x62ool\x18\x07 \x01(\x08\x12.\n\x04\x65num\x18\x08 \x01(\x0e\x32 .example.ExampleMessage.SomeEnum\x12\x0e\n\x06string\x18\t \x01(\t\x12&\n\x06nested\x18\n \x01(\x0b\x32\x16.example.NestedMessage\x12\x12\n\nstringlist\x18\x0b \x03(\t\x12\r\n\x05\x62ytes\x18\x0c \x01(\x0c\x12\x10\n\x08sfixed32\x18\r \x01(\x0f\x12\x10\n\x08sfixed64\x18\x0e \x01(\x10\x12\x0e\n\x06sint32\x18\x0f \x01(\x11\x12\x0e\n\x06sint64\x18\x10 \x01(\x12\x12\x0f\n\x07\x66ixed32\x18\x11 \x01(\x07\x12\x0f\n\x07\x66ixed64\x18\x12 \x01(\x06\x12\x15\n\x0boneofstring\x18\x13 \x01(\tH\x00\x12\x14\n\noneofint32\x18\x14 \x01(\x05H\x00\x12-\n\x03map\x18\x15 \x03(\x0b\x32 .example.ExampleMessage.MapEntry\x12-\n\ttimestamp\x18\x16 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x08\x64uration\x18\x17 \x01(\x0b\x32\x19.google.protobuf.Duration\x12(\n\x07\x64\x65\x63imal\x18\x18 \x01(\x0b\x32\x17.example.DecimalMessage\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"2\n\x08SomeEnum\x12\x0f\n\x0bunspecified\x10\x00\x12\t\n\x05\x66irst\x10\x01\x12\n\n\x06second\x10\x02\x42\x07\n\x05oneofb\x06proto3'
)


_SIMPLEMESSAGE = DESCRIPTOR.message_types_by_name["SimpleMessage"]
_NESTEDMESSAGE = DESCRIPTOR.message_types_by_name["NestedMessage"]
_DECIMALMESSAGE = DESCRIPTOR.message_types_by_name["DecimalMessage"]
_EXAMPLEMESSAGE = DESCRIPTOR.message_types_by_name["ExampleMessage"]
_EXAMPLEMESSAGE_MAPENTRY = _EXAMPLEMESSAGE.nested_types_by_name["MapEntry"]
_EXAMPLEMESSAGE_SOMEENUM = _EXAMPLEMESSAGE.enum_types_by_name["SomeEnum"]
SimpleMessage = _reflection.GeneratedProtocolMessageType(
    "SimpleMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIMPLEMESSAGE,
        "__module__": "example.example_pb2"
        # @@protoc_insertion_point(class_scope:example.SimpleMessage)
    },
)
_sym_db.RegisterMessage(SimpleMessage)

NestedMessage = _reflection.GeneratedProtocolMessageType(
    "NestedMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _NESTEDMESSAGE,
        "__module__": "example.example_pb2"
        # @@protoc_insertion_point(class_scope:example.NestedMessage)
    },
)
_sym_db.RegisterMessage(NestedMessage)

DecimalMessage = _reflection.GeneratedProtocolMessageType(
    "DecimalMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _DECIMALMESSAGE,
        "__module__": "example.example_pb2"
        # @@protoc_insertion_point(class_scope:example.DecimalMessage)
    },
)
_sym_db.RegisterMessage(DecimalMessage)

ExampleMessage = _reflection.GeneratedProtocolMessageType(
    "ExampleMessage",
    (_message.Message,),
    {
        "MapEntry": _reflection.GeneratedProtocolMessageType(
            "MapEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _EXAMPLEMESSAGE_MAPENTRY,
                "__module__": "example.example_pb2"
                # @@protoc_insertion_point(class_scope:example.ExampleMessage.MapEntry)
            },
        ),
        "DESCRIPTOR": _EXAMPLEMESSAGE,
        "__module__": "example.example_pb2"
        # @@protoc_insertion_point(class_scope:example.ExampleMessage)
    },
)
_sym_db.RegisterMessage(ExampleMessage)
_sym_db.RegisterMessage(ExampleMessage.MapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _EXAMPLEMESSAGE_MAPENTRY._options = None
    _EXAMPLEMESSAGE_MAPENTRY._serialized_options = b"8\001"
    _SIMPLEMESSAGE._serialized_start = 99
    _SIMPLEMESSAGE._serialized_end = 163
    _NESTEDMESSAGE._serialized_start = 165
    _NESTEDMESSAGE._serialized_end = 208
    _DECIMALMESSAGE._serialized_start = 210
    _DECIMALMESSAGE._serialized_end = 241
    _EXAMPLEMESSAGE._serialized_start = 244
    _EXAMPLEMESSAGE._serialized_end = 939
    _EXAMPLEMESSAGE_MAPENTRY._serialized_start = 836
    _EXAMPLEMESSAGE_MAPENTRY._serialized_end = 878
    _EXAMPLEMESSAGE_SOMEENUM._serialized_start = 880
    _EXAMPLEMESSAGE_SOMEENUM._serialized_end = 930
# @@protoc_insertion_point(module_scope)
